"""Add Session 2 authentication enhancements

Revision ID: 772d5e37a7a9
Revises: 94f921c56d98
Create Date: 2025-06-19 18:32:51.291966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '772d5e37a7a9'
down_revision: Union[str, Sequence[str], None] = '94f921c56d98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create ENUM type for user roles first
    op.execute("CREATE TYPE userrole AS ENUM ('USER', 'ADMIN', 'MODERATOR')")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_session_token'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_state'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_vm_instance_id'), table_name='sessions')
    op.alter_column('snapshots', 'size_bytes',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_index(op.f('ix_snapshots_created_at'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_name'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_user_id'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_vm_instance_id'), table_name='snapshots')
    # Add Session 2 authentication columns
    op.add_column('users', sa.Column('role', sa.Enum('USER', 'ADMIN', 'MODERATOR', name='userrole'), nullable=False, server_default='USER'))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.add_column('vm_instances', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('vm_instances', sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_vm_instances_created_at'), table_name='vm_instances')
    op.drop_index(op.f('ix_vm_instances_firecracker_id'), table_name='vm_instances')
    op.drop_index(op.f('ix_vm_instances_state'), table_name='vm_instances')
    op.drop_index(op.f('ix_vm_instances_user_id'), table_name='vm_instances')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_vm_instances_user_id'), 'vm_instances', ['user_id'], unique=False)
    op.create_index(op.f('ix_vm_instances_state'), 'vm_instances', ['state'], unique=False)
    op.create_index(op.f('ix_vm_instances_firecracker_id'), 'vm_instances', ['firecracker_id'], unique=False)
    op.create_index(op.f('ix_vm_instances_created_at'), 'vm_instances', ['created_at'], unique=False)
    op.drop_column('vm_instances', 'stopped_at')
    op.drop_column('vm_instances', 'started_at')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'role')
    # Drop ENUM type
    op.execute("DROP TYPE userrole")
    op.create_index(op.f('ix_snapshots_vm_instance_id'), 'snapshots', ['vm_instance_id'], unique=False)
    op.create_index(op.f('ix_snapshots_user_id'), 'snapshots', ['user_id'], unique=False)
    op.create_index(op.f('ix_snapshots_name'), 'snapshots', ['name'], unique=False)
    op.create_index(op.f('ix_snapshots_created_at'), 'snapshots', ['created_at'], unique=False)
    op.alter_column('snapshots', 'size_bytes',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_index(op.f('ix_sessions_vm_instance_id'), 'sessions', ['vm_instance_id'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_sessions_state'), 'sessions', ['state'], unique=False)
    op.create_index(op.f('ix_sessions_session_token'), 'sessions', ['session_token'], unique=False)
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    # ### end Alembic commands ###
