#!/usr/bin/env python3
"""Provision a device identity for the real-relay stack.

Runs `build-bridge provision` to mint a UUID device id + Ed25519 identity key +
X25519 transport key, then writes (into deploy/secrets/, git-ignored):

  - seed.sql      schema `build` + `devices` table + the approved device row
  - bridge.env    the private keys the bridge loads
  - gateway.env   the device id + transport public key the gateway serves

Idempotent: if deploy/secrets/identity.json already exists it is reused, so the
DB seed and the bridge keep matching across re-runs.

Usage: python3 deploy/provision.py [path-to-build-bridge-binary]
"""

import json
import os
import subprocess
import sys
import uuid

HERE = os.path.dirname(os.path.abspath(__file__))
SECRETS = os.path.join(HERE, "secrets")
DEFAULT_BIN = os.path.join(HERE, "..", "bridge", "target", "release", "build-bridge")


def main() -> int:
    os.makedirs(SECRETS, exist_ok=True)
    identity_path = os.path.join(SECRETS, "identity.json")

    if os.path.exists(identity_path):
        with open(identity_path) as f:
            ident = json.load(f)
        print(f"reusing existing identity {ident['device_id']}")
    else:
        binary = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_BIN
        if not os.path.exists(binary):
            binary = os.path.join(HERE, "..", "bridge", "target", "debug", "build-bridge")
        out = subprocess.run([binary, "provision"], capture_output=True, text=True, check=True)
        ident = json.loads(out.stdout)
        ident["owner_user_id"] = str(uuid.uuid4())
        with open(identity_path, "w") as f:
            json.dump(ident, f, indent=2)
        print(f"provisioned new identity {ident['device_id']}")

    write_seed(ident)
    write_bridge_env(ident)
    write_gateway_env(ident)
    print(f"wrote {SECRETS}/{{seed.sql,bridge.env,gateway.env}}")
    return 0


def write_seed(ident: dict) -> None:
    seed = f"""-- Generated by deploy/provision.py. The relay expects build-web to own the
-- schema, so we create the subset it reads and seed one approved device.
CREATE SCHEMA IF NOT EXISTS build;

CREATE TABLE IF NOT EXISTS build.devices (
    id uuid PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    name varchar(100) NOT NULL,
    public_key varchar(100) NOT NULL,
    transport_public_key varchar(100),
    owner_user_id uuid NOT NULL,
    approved boolean NOT NULL DEFAULT true,
    status varchar(20) NOT NULL DEFAULT 'offline',
    last_heartbeat_at timestamptz,
    heartbeat_interval_s integer NOT NULL DEFAULT 30,
    missed_heartbeat_windows text,
    CONSTRAINT uq_device_name_owner UNIQUE (name, owner_user_id)
);

INSERT INTO build.devices
    (id, name, public_key, transport_public_key, owner_user_id, approved, status, heartbeat_interval_s)
VALUES
    ('{ident['device_id']}', 'bridge-local', '{ident['ed25519_pub_b64_padded']}',
     '{ident['x25519_pub_b64_padded']}', '{ident['owner_user_id']}', true, 'offline', 30)
ON CONFLICT (id) DO NOTHING;
"""
    with open(os.path.join(SECRETS, "seed.sql"), "w") as f:
        f.write(seed)


def write_bridge_env(ident: dict) -> None:
    env = (
        f"BRIDGE_DEVICE_ID={ident['device_id']}\n"
        f"BRIDGE_IDENTITY_PRIV={ident['ed25519_priv_b64']}\n"
        f"BRIDGE_TRANSPORT_PRIV={ident['x25519_priv_b64']}\n"
        f"BRIDGE_TRANSPORT_PUB={ident['x25519_pub_b64']}\n"
    )
    with open(os.path.join(SECRETS, "bridge.env"), "w") as f:
        f.write(env)


def write_gateway_env(ident: dict) -> None:
    env = (
        f"DEVICE_ID={ident['device_id']}\n"
        f"DEVICE_TRANSPORT_PUB={ident['x25519_pub_b64']}\n"
    )
    with open(os.path.join(SECRETS, "gateway.env"), "w") as f:
        f.write(env)


if __name__ == "__main__":
    raise SystemExit(main())
